config/routes.rb
Rails.application.routes.draw do
  devise_for :users

  resources :videos, only: [:index, :show, :new, :create, :destroy]
  get '/watch/:id', to: 'users#watch', as: :watch
  get '/stream', to: 'users#stream', as: :stream

  root 'home#home'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/stream.rb
class Stream < ApplicationRecord
  before_create do |stream|
    session = OpenTokClient.create_session
    stream.opentok_session_id = session.session_id
  end

  belongs_to :user
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  has_one :stream
end

app/models/video.rb
class Video < ApplicationRecord
  mount_uploader :video, VideoUploader do
    def url(format = nil)
      uploaded_path = encode_path(file.path.sub(File.expand_path(root), ''))
      return uploaded_path if format.nil?
      files = Dir.entries(File.dirname(file.path))
      files.each do |f|
        next unless File.extname(f) == '.' + format.to_s
        return File.dirname(uploaded_path) + '/' + f
      end
    end
  end

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  before_action :authenticate_user!

  def home
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :authenticate_user!

  def stream
    @stream     = current_user.stream || current_user.create_stream
    gon.opentok = opentok_data(@stream)
  end

  def watch
    @stream = User.find(params[:id]).stream
    gon.opentok = opentok_data(@stream)
  end

  private

  def opentok_data(stream)
    token = OpenTokClient.generate_token(stream.opentok_session_id)
    { sessionId: stream.opentok_session_id, apiKey: Figaro.env.opentok_api_key, token: token }
  end
end

app/controllers/videos_controller.rb
class VideosController < ApplicationController
  before_action :authenticate_user!

  def index
    @videos = Video.order("created_at DESC").all
  end

  def show
    @video = Video.find(params[:id])
  end

  def new
    @videos = Video.new
  end

  def create
    @videos = Video.new(video_params)
    if @videos.save
      respond_to do |format|
        format.html {redirect_to videos_path, notice: 'Video Have been removed.'}
      end
    end
  end

  def destroy
    @video = Video.find(params[:id])
    if @video.delete
      respond_to do |format|
        format.html {redirect_to videos_path, notice: 'Video Have been removed.'}
      end
    end
  end

  private

  def video_params
    params.require(:video).permit(:title, :description, :video)
  end


end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/home/home.html.erb
<div class="container">
  <div class="btn btn-light">
  <%= link_to "Videos", videos_path %></br>
  </div>
  <div class="btn btn-light">
  <%= link_to "Start Streaming", stream_path %>
  </div>
  <% if user_signed_in? %>
    <%= link_to('Logout', destroy_user_session_path, method: :delete) %>
  <% else %>
    <%= link_to('Login', new_user_session_path)  %>
  <% end %>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <title>Live Stream</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
    <%= Gon::Base.render_data %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/users/stream.html.erb
<%= javascript_include_tag "//static.opentok.com/webrtc/v2.2/js/TB.min.js" %>
<h1>Your stream</h1>
<div id="publisher"></div>
Link to your stream: <%= link_to watch_url(@stream.user.id), watch_url(@stream.user.id) %>

app/views/users/watch.html.erb
<%= javascript_include_tag "//static.opentok.com/webrtc/v2.2/js/TB.min.js" %>
<h1><%= @stream.user.email %>'s stream</h1>
<div id="stream"></div>

app/views/videos/_videos.html.erb
  <% @videos.each do |video| %>
<div>
    <h2><%= link_to "#{video.title}", video_path(video) %></h2>
    <%= video_tag(video.video_url.to_s, :controls => true) %>
</div>
  <% end %>

app/views/videos/index.html.erb
<div class="btn btn-light">
  <%= link_to "Create New Video", new_video_path %></br>
</div>
<div>
  <%= render partial: 'videos' %>
</div>

app/views/videos/new.html.erb
<div>
  <%= form_for(@videos) do |f|%>
  <div class="form-group">
    <%= f.label :title, "Title" %>
    <%= f.text_field :title, class:"form-control", placeholder: "Insert Title" %></br>
    <%= f.label :description, "Description" %>
    <%= f.text_area :description, class:"form-control", placeholder: "Insert description" %></br>
    <%= f.label :video, "Upload Video" %>
    <%= f.file_field :video, class:"form-control-file" %></br>
    <%= f.submit "Submit", class: 'btn btn-primary' %>
  </div>
  <% end %>
</div>

app/views/videos/show.html.erb
<div>
  <h1><%= @video.title %></h1>
  <div>
    <%= video_tag(@video.video_url.to_s, :controls => true) %>
  </div>
  <p><%= @video.description %></p>
    <%= link_to "Delete", video_path(@video), method: :delete, data: { confirm: "Are you sure?" } %>
</div>